version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
